version: '3.8'

services:
  web:
    build: .
    container_name: api_realtime_php
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - CPANEL_API_URL=https://u-logistic-ai.uz/api.php
      - GOOGLE_MAPS_API_KEY=AIzaSyAd4rEAQqf58fCJGABqW99teDP9BcuyN08
    command: >
      gunicorn app:app
      --bind 0.0.0.0:5000
      --timeout 120
    restart: unless-stopped
